// Copyright 2023 MooZ (@Modbox)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//BOOTMAGIC
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

//RGB LED STRIP
#define WS2812_DI_PIN GP16 //GP14
#define RGBLED_NUM 1
#define RGBLIGHT_LED_COUNT RGBLED_NUM
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_LIMIT_VAL 180 // brillo máximo
#define RGBLIGHT_SLEEP 

//RGB LAYER CHANGE
#define RGBLIGHT_LAYERS
#define RGBLIGHT_DEFAULT_HUE 128  // Start with cyan
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 200
